name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: install
      run: npm install

    - name: lint
      run: npm run lint

    - name: test
      run: npm run test -- --passWithNoTests

    - name: build
      run: npm run build
